# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
m = np.random.random((3,3,3))
print(m)

[[[0.7049217  0.64824869 0.34824456]
  [0.75544506 0.32742442 0.38704067]
  [0.04607169 0.08039551 0.42687688]]

 [[0.17965157 0.14382494 0.69027729]
  [0.32606612 0.41225814 0.09395497]
  [0.9711706  0.08175179 0.98377517]]

 [[0.05065088 0.3844438  0.1430752 ]
  [0.53467753 0.78013817 0.41887928]
  [0.55418918 0.55395887 0.00746117]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
import numpy as np
m = np.random.random((5,5))
m=np.diag(1+np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [5]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.65805679  1.69046861  1.93298732  0.16498031 -1.32962927]
 [-0.12836132 -0.9206071   1.02073316  0.78862954 -1.17322436]
 [ 1.46402816 -0.92522272  0.19624028  0.75286865 -1.25736771]
 [ 0.67845128 -0.24469905 -1.32468234 -0.25976554  0.83633571]
 [-0.94790049 -1.29173726  0.76610839  0.74707248 -0.57764994]]


# 5.  How to find common values between two arrays?

In [6]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 4 6 8 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-08-16
2020-08-17
2020-08-18


# 7. Consider two random array A and B, check if they are equal

In [13]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [15]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


[0.83813718 0.4104576  0.55112626 0.         0.16368674 0.52983411
 0.57609036 0.54627013 0.35026971 0.26966855]


# 9. How to print all the values of an array?

In [16]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [17]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-0.04253569  0.21318226 -0.57834995  0.22597066 -0.00658135 -0.08565479
   0.19935394  0.20442804  0.37088304 -0.50069617]
 [-0.29888357  0.07419605  0.15491735 -0.0180165  -0.03784772  0.18176257
   0.43016755 -0.39026575  0.22573641 -0.32176639]
 [-0.04061625 -0.04086962 -0.38838716 -0.02518596  0.17696484  0.30719335
   0.24936508  0.18819272 -0.06716766 -0.35948934]
 [-0.09236828  0.00508035  0.30565274  0.22508767 -0.48375713 -0.03698177
  -0.28190783  0.31762722  0.26674877 -0.22518174]
 [ 0.29515902 -0.11241139 -0.36002239  0.3601158  -0.49007959 -0.34917226
   0.1448598   0.38312305  0.32521298 -0.19678502]]
[[-0.04253569  0.21318226 -0.57834995  0.22597066 -0.00658135 -0.08565479
   0.19935394  0.20442804  0.37088304 -0.50069617]
 [-0.29888357  0.07419605  0.15491735 -0.0180165  -0.03784772  0.18176257
   0.43016755 -0.39026575  0.22573641 -0.32176639]
 [-0.04061625 -0.04086962 -0.38838716 -0.02518596  0.17696484  0.30719335
   0.24936508  0.18819272 -0.06716766 -0.35948934]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 6. 3. 2. 3. 3. 3. 2. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [19]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.83842114 0.10495212 0.08682198 0.41182635 0.8119946 ]
 [0.08591427 0.9976277  0.64251129 0.76660882 0.13065871]
 [0.24506388 0.31879674 0.54413305 0.27297336 0.99261737]
 [0.37015517 0.9913599  0.205646   0.10079382 0.53601287]
 [0.6043183  0.74885388 0.07697843 0.81842184 0.08001467]]
[[0.63206377 0.97623258 0.87097716 0.76906921 0.96710511]
 [0.83208813 0.84053081 0.41864043 0.11787624 0.0219364 ]
 [0.08923418 0.36118721 0.76774202 0.58939787 0.26817831]
 [0.73135394 0.72271635 0.78140963 0.51475325 0.42435844]
 [0.32841032 0.02806771 0.6064197  0.16673156 0.27875209]]
diagonal of a dot product method 1 is.... [1.19287076 1.71218401 1.5799068  0.66399424 0.99111888]
diagonal of a dot product method 2 is.... [1.19287076 1.71218401 1.5799068  0.66399424 0.99111888]


# 13.How to find the most frequent value in an array?

In [20]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[5 5 8 1 5 5 7 1 0 3 8 3 5 4 6 8 7 5 2 3 1 2 9 3 4 6 6 3 1 7 5 7 7 1 4 8 6
 3 8 2 0 0 5 5 0 7 6 0 2 8]
5


# 14.How to get the n largest values of an array

In [21]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [22]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
